name: integration
on: [push, pull_request, workflow_dispatch]
jobs:
  t:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-baseimage: [ubuntu, opensuse.leap]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test 001-smoke.sh on ${{ matrix.docker-baseimage }}
        run: |
          cd test/integration/environs && ./001-smoke.sh
        env:
          ENVIRON_DOCKERFILE: Dockerfile.environs.${{ matrix.docker-baseimage }}
          
      - name: Test 002-autoindex-format-0.t
        run: |
          cd test/integration/environs && ./002-autoindex-format-0.sh
        env:
          ENVIRON_DOCKERFILE: Dockerfile.environs.${{ matrix.docker-baseimage }}

      - name: Test 002-autoindex-format-1.t
        run: |
          cd test/integration/environs && ./002-autoindex-format-1.sh
        env:
          ENVIRON_DOCKERFILE: Dockerfile.environs.${{ matrix.docker-baseimage }}

      - name: Test 002-autoindex-format-2.t
        run: |
          cd test/integration/environs && ./002-autoindex-format-2.sh
        env:
          ENVIRON_DOCKERFILE: Dockerfile.environs.${{ matrix.docker-baseimage }}
